config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    resources :build, only: [:show, :update], controller: 'orders/build'
  end

  resources :line_items

  resources :carts

  resources :products

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :shops

  devise_for :accounts
  devise_for :users

  namespace :api do
    devise_scope :user do
      post "sign_in", to: "sessions#create"
    end
  end

  root 'pages#home'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items 

  def add_product(product_args)
    current_item = line_items.find_by(product_id: product_args[:product_id])
    # puts current_item.inspect
    # puts product_args
    # puts product_args[:quantity]
    if current_item
      current_item.quantity += product_args[:quantity].to_i
      current_item.save
    else
      current_item = line_items.build(product_args)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
  # include CurrentCart
  # before_action :set_cart, only: [:show]

  private

    def cart_params
      params.require(:cart).permit()
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'carts' %>
<% end %>

<p id="notice"><%= notice %></p>

<div class="col-md-7 col-sm-12 text-left">
  <ul>
    <li class="row list-inline columnCaptions">
      <span>QTY</span>
      <span>ITEM</span>
      <span>Price</span>
    </li>
    <% @cart.line_items.each do |item| %>
      <li class="row">
        <span class="quantity"><%= item.quantity %></span>
        <span class="itemName"><%= item.product.name %></span>
        <span class="popbtn"><a class="arrow"></a></span>
        <span class="price"><%= item.product.price %></span>
      </li>
    <% end %>
  </ul>
</div>


<%= button_to "Checkout", new_order_path, :method => :get %>
<%= button_to "Empty cart", @cart, :method => :delete, data: { confirm: 'Are you sure you want to delete this alert?' } %>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>